import os

Schedule = []                

# # =================================== CLASSIFIER ========================================
# # ================== TRAINING AND TESTING ========================
# # Source: AMAZON_RO
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO                        --mode classifier --phase train --runs 5 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 150 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset AMAZON_RO  --mode classifier --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset AMAZON_PA  --mode classifier --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA --mode classifier --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# # Source: AMAZON_PA
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_PA                        --mode classifier --phase train --runs 5 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 150 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_PA --t_dataset AMAZON_PA  --mode classifier --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_PA --t_dataset AMAZON_RO  --mode classifier --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_PA --t_dataset CERRADO_MA --mode classifier --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# # Source: CERRADO_MA
# Schedule.append("python Main_Train_Test.py --s_dataset CERRADO_MA                        --mode classifier --phase train --runs 5 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 150 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset CERRADO_MA --t_dataset CERRADO_MA --mode classifier --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset CERRADO_MA --t_dataset AMAZON_PA  --mode classifier --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset CERRADO_MA --t_dataset AMAZON_RO  --mode classifier --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# # ================================ CALCULATING METRICS ====================================
# # Source: AMAZON_RO
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset AMAZON_RO  --mode classifier --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset AMAZON_PA  --mode classifier --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset CERRADO_MA --mode classifier --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# # Source: AMAZON_PA
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_PA  --t_dataset AMAZON_PA  --mode classifier --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_PA  --t_dataset AMAZON_RO  --mode classifier --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_PA  --t_dataset CERRADO_MA --mode classifier --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# # Source: CERRADO_MA
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset CERRADO_MA --t_dataset CERRADO_MA --mode classifier --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset CERRADO_MA --t_dataset AMAZON_PA  --mode classifier --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset CERRADO_MA --t_dataset AMAZON_RO  --mode classifier --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")

# --------------------------------

# =================================== ADAPTATION ========================================
# ================== TRAINING AND TESTING ========================
# =========== Source: AMAZON_RO ============
# Target: CERRADO_MA
Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA --mode adaptation --match early  --phase train --runs 1 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA --mode adaptation --match early  --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset CERRADO_MA --mode adaptation --match early  --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
Schedule.append("python Main_Compute_Create_Avg_Precision_Recall_Curve_Avg_Hit_map.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA")

# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA --mode adaptation --match middle --phase train --runs 1 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA --mode adaptation --match middle --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset CERRADO_MA --mode adaptation --match middle --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Create_Avg_Precision_Recall_Curve_Avg_Hit_map.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA")

# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA --mode adaptation --match end    --phase train --runs 1 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA --mode adaptation --match end    --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset CERRADO_MA --mode adaptation --match end    --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Create_Avg_Precision_Recall_Curve_Avg_Hit_map.py --s_dataset AMAZON_RO --t_dataset CERRADO_MA")

# # Target: AMAZON_PA
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset AMAZON_PA  --mode adaptation --match early  --phase train --runs 1 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset AMAZON_PA  --mode adaptation --match early  --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset AMAZON_PA --mode adaptation --match early  --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")

# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset AMAZON_PA  --mode adaptation --match middle --phase train --runs 1 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset AMAZON_PA  --mode adaptation --match middle --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset AMAZON_PA --mode adaptation --match middle --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")

# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset AMAZON_PA  --mode adaptation --match end    --phase train --runs 1 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_RO --t_dataset AMAZON_PA  --mode adaptation --match end    --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset AMAZON_PA --mode adaptation --match end    --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")

# # =========== Source: AMAZON_PA ============
# # Target: AMAZON_RO
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_PA --t_dataset AMAZON_RO  --mode adaptation --match middle --phase train --runs 5 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_PA --t_dataset AMAZON_RO  --mode adaptation --match middle --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# # Target: CERRADO_MA
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_PA --t_dataset CERRADO_MA --mode adaptation --match middle --phase train --runs 5 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset AMAZON_PA --t_dataset CERRADO_MA --mode adaptation --match middle --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")

# # ========== Source: CERRADO_MA ============
# # Target: AMAZON_PA
# Schedule.append("python Main_Train_Test.py --s_dataset CERRADO_MA --t_dataset AMAZON_PA --mode adaptation --match middle --phase train --runs 5 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset CERRADO_MA --t_dataset AMAZON_PA --mode adaptation --match middle --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# # Target: AMAZON_RO
# Schedule.append("python Main_Train_Test.py --s_dataset CERRADO_MA --t_dataset AMAZON_RO --mode adaptation --match middle --phase train --runs 5 --patches_dimension 128 --image_channels 7 --num_classes 2 --epochs 100 --batch_size 32 --ada_batch_size 1 --patience 10 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")
# Schedule.append("python Main_Train_Test.py --s_dataset CERRADO_MA --t_dataset AMAZON_RO --mode adaptation --match middle --phase test  --patches_dimension 128 --image_channels 7 --num_classes 2 --batch_size 32 --ada_batch_size 1 --lr 0.0001 --optimizer Adam --data_augmentation True --fixed_tiles True --balanced_tr True --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --porcent_of_last_reference_in_actual_reference 100 --porcent_of_positive_pixels_in_actual_reference 2 --data_type .npy --dataset_main_path ../../..//Datasets/")

# ================================ CALCULATING METRICS ====================================
# # Source: AMAZON_RO
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset CERRADO_MA --mode adaptation --match early  --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset CERRADO_MA --mode adaptation --match middle --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset CERRADO_MA --mode adaptation --match end    --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")

# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset AMAZON_PA --mode adaptation --match early  --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset AMAZON_PA --mode adaptation --match middle --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_RO  --t_dataset AMAZON_PA --mode adaptation --match end    --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")

# # Source: AMAZON_PA
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_PA  --t_dataset AMAZON_RO  --mode adaptation --match middle --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset AMAZON_PA  --t_dataset CERRADO_MA --mode adaptation --match middle --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# # Source: CERRADO_MA
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset CERRADO_MA --t_dataset AMAZON_PA  --mode adaptation --match middle --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")
# Schedule.append("python Main_Compute_Metrics_MT.py --s_dataset CERRADO_MA --t_dataset AMAZON_RO  --mode adaptation --match middle --dataset_main_path ../../..//Datasets/ --Npoints 200 --eliminate_regions True --area_avoided 69 --buffer True --buffer_dimension_out 2 --buffer_dimension_in 0 --image_channels 7 --patches_dimension 128 --fixed_tiles True --data_type .npy")


for i in range(len(Schedule)):
    os.system(Schedule[i])
